name: Backend Tests on Pull Request
on:
  pull_request:
    paths:
      - "backend/**"
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Change directory to backend and install dependencies
        run: |
          cd backend
          npm install
      - name: Check style with ESLint
        run: |
          cd backend
          npm run lint
      - name: Run tests
        run: |
          cd backend
          npm run test
